### ISSUE TITLE
Context in OnLaunch

### ISSUE THREAD

**Issue by teriansilva** [ElvenMonky/AlexaSkillsKit.NET#4]
To detect if the device has a display, I use the context (context.System.Device.SupportedInterfaces.Display). But right now, its only present in OnIntent, not in OnLaunch. If the user launches the Skill without an intent, it could not detect if the device has a display.

I would make the code changes and create a PR in this fork. Before I do this, maybe you guys have another solution to approach this problem? Thanks!

**Comment by ElvenMonky** [comment]
I completely missed that context is present in all requests. Please, open an issue in the AreYouFreeBusy repo.
